### ISSUE TITLE
HTML - <br> ?

### ISSUE THREAD

**Issue by RicCastelhano** [CarlosAlenquer/Hoop#2]
Qual é o intuito destes `<br>` ?

```
<ul>
        <li><a href="#Produto">Produto</a></li><br><br>
        <li><a href="#">Pricing</a></li><br><br>
        <li><a href="#">Parceiros</a></li><br><br>
        <li><a href="#">Sobre nós</a></li><br><br>
        <li><a href="#">Contactos</a></li><br><br>
</ul>
```

**Comment by CarlosAlenquer** [comment]
Boa tarde Professor, para dar o espaçamento correto no footer, devia ter sido feito de outra maneira, mas foi de forma a que os items não ficassem colados uns aos outros.

**Comment by CarlosAlenquer** [comment]
Em vez da utilização dos '< br >' poderia ter sido tudo feito no CSS.

**Comment by RicCastelhano** [comment]
Yep, deveria ter sido via CSS :)
