### ISSUE TITLE
HTML - injecção de JS no HTML ?

### ISSUE THREAD

**Issue by RicCastelhano** [CarlosAlenquer/Hoop#4]
Porque injectaram o JavaScript no HTML desta forma?
Imaginando que eu não queria ter esse JS a correr, não me basta mexer no ficheiro JS certo?

`118.             <script>showSlidesCycle();</script>`

**Comment by CarlosAlenquer** [comment]
Neste caso foi para a chamar a segunda função no ficheiro do slideshow.js para iniciar o ciclo automático de mudança de slide, quando chamávamos a função dentro do próprio js, não acontecia nada.

**Comment by RicCastelhano** [comment]
O método deveria ser invocado quando o DOM estivesse `ready`.

**Comment by CarlosAlenquer** [comment]
Agora já percebi! Obrigado!
