### ISSUE TITLE
JavaScript - erro a correr a página

### ISSUE THREAD

**Issue by RicCastelhano** [CarlosAlenquer/Hoop#5]
Estou a obter este erro na consola quando abro a página no browser. 

```
Uncaught TypeError: Cannot read property 'style' of undefined
    at showSlides (slideshow.js:21)
    at slideshow.js:3
```

**Comment by CarlosAlenquer** [comment]
Está relacionado com esta linha -> slides[slideIndex-1].style.display = "block";

Esta linha serve para mostrar a imagem que deve estar atualmente vísivel no slideshow da página. 

Possivelmente pode ser uma questão de mudar a linha no topo da função: 
var slides = document.getElementsByClassName("mySlides"); 

visto que os testemunhos tao definidos em divs com o nome de class="mySlides fade"

Ou pode faltar algum tipo de verificação de validação antes de executar a linha: slides[slideIndex-1].style.display = "block";

**Comment by CarlosAlenquer** [comment]
Coloquei esta verificação antes da linha que põe a imagem atualmente vísivel no slideshow da página: 

if(slides[slideIndex-1] != undefined)
  slides[slideIndex-1].style.display = "block";

deste modo não coloca o style.display block quando é undefined, se testar este código já não vai dar erro.

**Comment by RicCastelhano** [comment]
A solução certa não é essa :) A questão está na forma em que fazes o `slideIndex-1`. Estás a cair num indice onde nao consta objecto.

**Comment by CarlosAlenquer** [comment]
Sim é verdade nessa posição o objeto não existe no array :(
